### ISSUE TITLE
Lights on throws error 

### ISSUE THREAD

**Issue by kikohnl** [schemers/homebridge-screenlogic#18]
Turning on lights does not work:

[4/25/2021, 7:26:51 PM] [ScreenLogic] _pollForStatus success, retryAttempt: 0
[4/25/2021, 7:26:53 PM] [ScreenLogic] setOn: true { name: 'Pool Color Blue', cmd: 13 }
[4/25/2021, 7:26:53 PM] [homebridge-screenlogic] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[4/25/2021, 7:26:53 PM] [homebridge-screenlogic] Error: 
    at On.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1663:22
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SetColorAccessory.setOn (/usr/lib/node_modules/homebridge-screenlogic/src/setColorAccessory.ts:122:5)
    at On.<anonymous> (/usr/lib/node_modules/homebridge-screenlogic/src/setColorAccessory.ts:84:18)
    at On.emit (events.js:314:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
[4/25/2021, 7:26:53 PM] [ScreenLogic] sendLightCommand: successfully sent light command:  13
[4/25/2021, 7:26:55 PM] [ScreenLogic] connected: XX-XX-XX (getStatus)
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateCurrentTemperature: 19.444444444444443 { displayName: 'Air', type: 'Air' }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateStatusActive: true { displayName: 'Air', type: 'Air' }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateCurrentTemperature: 18.333333333333332 { displayName: 'Pool', type: 'Pool' }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateStatusActive: false { displayName: 'Pool', type: 'Pool' }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateCurrentTemperature: 18.333333333333332 { displayName: 'Spa', type: 'Spa' }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateStatusActive: false { displayName: 'Spa', type: 'Spa' }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateCurrentTemperature: 18.333333333333332 {
  displayName: 'Pool Heater',
  bodyType: 0,
  minSetPoint: 4.444444444444445,
  maxSetPoint: 40
}
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateTargetTemperature: 30 {
  displayName: 'Pool Heater',
  bodyType: 0,
  minSetPoint: 4.444444444444445,
  maxSetPoint: 40
}
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateCurrentHeatingCoolingState: 0 {
  displayName: 'Pool Heater',
  bodyType: 0,
  minSetPoint: 4.444444444444445,
  maxSetPoint: 40
}
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateTargetHeatingCoolingState: 0 {
  displayName: 'Pool Heater',
  bodyType: 0,
  minSetPoint: 4.444444444444445,
  maxSetPoint: 40
}
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateCurrentTemperature: 18.333333333333332 {
  displayName: 'Spa Heater',
  bodyType: 1,
  minSetPoint: 4.444444444444445,
  maxSetPoint: 40
}
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateTargetTemperature: 39.9 {
  displayName: 'Spa Heater',
  bodyType: 1,
  minSetPoint: 4.444444444444445,
  maxSetPoint: 40
}
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateCurrentHeatingCoolingState: 0 {
  displayName: 'Spa Heater',
  bodyType: 1,
  minSetPoint: 4.444444444444445,
  maxSetPoint: 40
}
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateTargetHeatingCoolingState: 0 {
  displayName: 'Spa Heater',
  bodyType: 1,
  minSetPoint: 4.444444444444445,
  maxSetPoint: 40
}
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Spa', id: 500 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: true { displayName: 'Aux 1', id: 501 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Aux 2', id: 502 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Aux 3', id: 503 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Pool', id: 505 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Feature 1', id: 510 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Feature 2', id: 511 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Feature 3', id: 512 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Feature 4', id: 513 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Feature 5', id: 514 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Feature 6', id: 515 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Feature 7', id: 516 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'Feature 8', id: 517 }
[4/25/2021, 7:26:55 PM] [ScreenLogic] updateOn: false { displayName: 'AuxEx', id: 519 }

**Comment by schemers** [comment]
Sorry for the delayed response. Can you start Homebridge with debug turned on? And then send the log output for that? That might help debug.
