### ISSUE TITLE
Only one light shows up/callback function error

### ISSUE THREAD

**Issue by lucanaut** [schemers/homebridge-screenlogic#20]
Looking at my screen logic controller, the two lights in my pool are separate (two separate switches in the app).  Should they appear separately on the Home app?  I only see one switch.  Not sure if related, but I also get this message:

[homebridge-screenlogic] Error: This callback function has already been called by someone else; it can only be called one time.
See https://git.io/JtMGR for more info.
[5/17/2021, 8:16:06 PM] [homebridge-screenlogic] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-screenlogic/src/platform.ts:400:7)
    at On.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at On.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:24)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2103:22)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75

**Comment by schemers** [comment]
They should be separate. I see a pool lint switch and a spa light switch, for example. It could be something particular to your system.

Starting Homebridge in debug mode should provide extra information in the log that might help debug.
